### ISSUE TITLE
Hello，您好，demo中开着视频，运行几分钟就会崩溃，是什么原因呢？

### ISSUE THREAD

**Issue by HeZhengLin** [horsefaced/AgoraCLI#10]
Hello，您好，demo中开着视频，Debug模式下运行几分钟就会崩溃，是什么原因呢？
![qq 20170925180625](https://user-images.githubusercontent.com/22746371/30803488-5ae2da2c-a21c-11e7-851d-78033035e7a1.png)

**Comment by horsefaced** [comment]
呃，我没长时间挂着试过，大约多长时间这样子

发自我的 iPhone

**Comment by HeZhengLin** [comment]
debug调试运行的话5分钟左右，如果直接运行时间稍微长点8到10分钟

**Comment by horsefaced** [comment]
好的，我去试试

发送自 Windows 10 版邮件应用

发件人: HeZhengLin
发送时间: 2017年9月26日 14:07
收件人: horsefaced/AgoraCLI
抄送: horsefaced; Comment
主题: Re: [horsefaced/AgoraCLI]=?UTF-8?Q?_Hello=EF=BC=8C=E6=82=A8=E5=A5=BD=EF=BC=8Cdemo=E4=B8=AD=E5=BC=80=E7=9D=80=E8=A7=86=E9=A2=91=EF=BC=8C=E8=BF=90=E8=A1=8C=E5=87=A0=E5=88=86=E9=92=9F=E5=B0=B1=E4=BC=9A=E5=B4=A9=E6=BA=83=EF=BC=8C=E6=98=AF=E4=BB=80=E4=B9=88=E5=8E=9F=E5=9B=A0=E5=91=A2=EF=BC=9F?==?UTF-8?Q?_=28#10=29?=

debug调试运行的话5分钟左右，如果直接运行时间稍微长点8到10分钟

**Comment by HeZhengLin** [comment]
好的，谢谢了！

**Comment by diegoeddy** [comment]
闪退是由于内存泄露造成的。内存泄露的原因还没找到

**Comment by gaokaige** [comment]
遇到同样的问题。release版的程序，运行几分钟就崩溃了；

**Comment by horsefaced** [comment]
不好意思,近来比较忙,一直没时间查这个问题, 今天用声网1.14的测试, 看进程运行内存是一直在涨, GC也没有效果, 我查一下是我这边代码哪里有问题还是声网的部分有问题.

**Comment by horsefaced** [comment]
已经修改了原始数据API里会造成内存泄漏的问题, 但只是暂时的方案, 因为如果在图像大小改变的情况下还是会造成内存泄漏的问题. 一般情况下, 只要不通过原始数据API改变原始图像的整体大小, 比如从640x480变成320X240之类的, 就不会有这个问题. 我还要查一下怎么才能完全解决掉. 各位有什么建议欢迎帮帮忙.

**Comment by diegoeddy** [comment]
其实用1.14的release版运行就不会出现内存泄露的问题了，至少内存增长的很慢。

**Comment by horsefaced** [comment]
其实因为改过了, 哈哈哈哈.
