### ISSUE TITLE
您好，信令部分。呼叫能成功，但接受拒绝都没有回调，请问我哪里有问题？

### ISSUE THREAD

**Issue by JethorJ** [horsefaced/AgoraCLI#11]
大神您好，我使用您的DEMO修改了一下，发送信令没问题。想通过信令的呼叫方法实现一些功能。
实测呼叫时，对端能够收到呼叫信息，但无论对端是接受还是拒绝，本地端都无法收到对应的回调，请问是这个部分暂时还不支持还是我使用的方式有问题呢？

**Comment by horsefaced** [comment]
信令这部分因为声网一直是beta版本,所以我其实就一直没更新过信令的SDK,还是最早期的版本.

**Comment by JethorJ** [comment]
大神您好，咨询一个问题。我用您的项目编译以后能够本机运行，但换其他机器上，总是报错。提示KernalBase.dll错误，找不到文件。请问这个如何解决。我不太懂VC，谢谢。

**Comment by horsefaced** [comment]
你这个错误是 kernalbase.dll找不到产生的, 你全机查找一下有没有这个dll, 如果没有最快的做法是重装系统, 或者安装一下sp1之类的.

> 在 2017年10月12日，11:19，JethorJ <notifications@github.com> 写道：
> 
> KernalBase.dll
