### ISSUE TITLE
大神，请问一下换机器运行的问题。

### ISSUE THREAD

**Issue by JethorJ** [horsefaced/AgoraCLI#12]
大神您好，咨询一个问题。我用您的项目编译以后能够本机运行，但换其他机器上，总是报错。提示KernalBase.dll错误，找不到文件。请问这个如何解决。我不太懂VC，谢谢。

**Comment by JethorJ** [comment]
编译的系统是Windows10,运行系统是WIN7，暂时还没安装SP1，已经安装了c++ redistributable 2017

**Comment by JethorJ** [comment]
另外我测试过了，机器里安装了VS的，就能运行，没有安装VS则不能运行。看样子是缺少了某个运行环境。

**Comment by horsefaced** [comment]
哦， 那你看项目的readme文件，里面有说明，要安装visual studio c++ 的包
发送自 Windows 10 版邮件应用

发件人: JethorJ
发送时间: 2017年10月13日 9:21
收件人: horsefaced/AgoraCLI
抄送: Subscribed
主题: Re: [horsefaced/AgoraCLI] 大神，请问一下换机器运行的问题。 (#12)

另外我测试过了，机器里安装了VS的，就能运行，没有安装VS则不能运行。看样子是缺少了某个运行环境。

**Comment by JethorJ** [comment]
大神您好，请问能留下一个联系方式么？比如邮件或者方便的工作QQ。您说的visual studio c++的包是指哪些？我已经安装了c++ redistributable2005-2017的各个版本，不知道还需要安装哪些呢？Readme文件我看过了，还是没太明白。我是做C#的，对于C++实在是小白一个，给您添麻烦了。

**Comment by horsefaced** [comment]
应该只要安装最新的一个就可以了

发自我的 iPhone

**Comment by JethorJ** [comment]
问题是，我都安装了，运行也还是不好使啊。不安装整个Visual Stuido，运行就会报错。

**Comment by JethorJ** [comment]
如果可以，您也可以加我QQ：75492789，或者邮箱：6687964@163.com
