### ISSUE TITLE
C# winform 使用信令呼叫APP用户,被对方接受后堆栈溢出

### ISSUE THREAD

**Issue by qulijun** [horsefaced/AgoraCLI#14]
signal.onInviteAcceptedByPeer += new onInviteAcceptedByPeer(onInviteAcceptedByPeer);//呼叫被对方接受时回调
private void onInviteReceivedByPeer(string channelId, string account, int uid)
        {
            log("对方已接受",0);
        }

AgoraClrLibrary.dll!<Module>.AgoraClrLibrary.AgoraClrSignalCallback.onInviteAcceptedByPeer(sbyte* channelID, uint channelID_size, sbyte* account, uint account_size, uint uid, sbyte* extra, uint extra_size)	未知
上面方法无限调用,已超出 Visual Studio 支持的最多堆栈帧数。

**Comment by horsefaced** [comment]
BUG已修改

**Comment by qulijun** [comment]
十分感谢，问题解决了。
