### ISSUE TITLE
手机APP使用信令呼叫 C# winform,收到信令,接受后视频不显示,使用了ChannelKey

### ISSUE THREAD

**Issue by qulijun** [horsefaced/AgoraCLI#15]
signal.onInviteReceived += new onInviteReceived(onInviteReceived);//收到呼叫
private void onInviteReceived(string channelId, string account, int uid, string extra)
        {
          DialogResult result = MessageBox.Show("呼叫","是否接受",MessageBoxButtons.YesNo);
          if (result == DialogResult.Yes)
          {
              //signal.channelLeave(channelId);
              //agora.leaveChannel();
              log("接收到呼叫" + channelId + "|" + account + "|" + uid + "|" + extra, 0);
              signal.channelInviteAccept(channelId, account);//接受
              signal.channelJoin(channelId);
             
              Dictionary<String, String> dic = new Dictionary<string, string>();
                dic.Add("channel", channelId);
                dic.Add("uid", "0");
                String res = HttpRequest.Post("/channelKey/channeKsys", dic);
                JObject jb = (JObject)JsonConvert.DeserializeObject(res);
                if ((int)jb["code"] == 1)
                {
                    //失败
                    MessageBox.Show((String)jb["message"]);
                    return;
                }
                else
                {
                    String channelkey = (String)jb["data"];//ChannelKey4
                    log("join channel", agora.joinChannel(channelkey, channelId, null, 0));//加入频道
                    log("enableVideo", agora.enableVideo());
                    log("startPreview", agora.startPreview());
                }
          }
          else
          {
              signal.channelInviteRefuse(channelId,account,extra);
              signal.channelLeave(channelId);
              agora.leaveChannel();
          }
   
        }

**Comment by horsefaced** [comment]
你查一下channelid是不是对的，然后查一下生成了channelkey是不是对的。如果都是对的话，joinchnnael后，android那边有没有收到用户加入的事件

**Comment by qulijun** [comment]
多谢提醒,问题已经解决:
经查是channelkey 的问题,两边得到channelkey的算法不同, 
static int ts = (int)(new Date().getTime()/1000);
static int r = new Random().nextInt();
static int expiredTs = 0;// 都是本地生成的,这里的值不同
