### ISSUE TITLE
2.0版本，在摄像头被占用的情况下，调用Dispose会死循环

### ISSUE THREAD

**Issue by wt616** [horsefaced/AgoraCLI#16]
如题，遇到Bug的具体方式如下（100%发生）：

1、电脑上只有一个摄像头，我是笔记本自带的，在开启AgoraCLI应用前，先用别的第三方程序把摄像头打开
2、启动自己的AgoraCLI，加入Channel并开始本地视频，此时本地视频区域就无法显示本地摄像头了（如果不是第1部的操作占用，则一定会显示出来）
3、在这种情况下，关闭时C#调用Dispose方法或Release方法时就会卡在这，有死循环的感觉。查看了您C++部分的Release实现，有递归调用

具体卡死的代码如下：
agora.Dispose();

由于我的Windows C#版本要反复进入，因此这个代码我不得不调用

**Comment by horsefaced** [comment]
你能把代码贴上来看一下吗？具体那个递归代码段

**Comment by wt616** [comment]
C#调用agora.Dispose();函数时卡死，前提是遇到了摄像头被其他应用占用着的情况
在IAgoraRtcEngine.h文件中，看到
bool queryInterface(C1* c, C2 iid) {
        pointer_type p = NULL;
        if (c && !c->queryInterface(iid, (void**)&p))
        {
            reset(p);
        }
        return p != NULL;;
	}
这个函数是递归调用，我猜测可能这里有问题，但我C++不太懂，也不知道怎么Debug你这段，非常明确的一点就是之前那个1.6的版本，在摄像头被占用时，release不会卡死，但是这次2.0就会。

我建议您自己也试试看，比较好复现。不管怎样，多亏您开发的这套中间件，让我开发方便许多，非常感谢！

**Comment by horsefaced** [comment]
好的，我看看

**Comment by horsefaced** [comment]
这问题是声网的问题，我测试过了，2.0.2最新的就没有这个问题了。你可以直接下它的2.0.2或者今天的2.0.3的sdk，把agora_rtc_sdk.dll直接换掉就可以了。

谢谢反馈。

**Comment by wt616** [comment]
感谢大神，果然好了

**Comment by tomato77** [comment]
请问，摄像头占用，我把agora_rtc_sdk.dll 直接换成2.0.2之后未能加载文件或程序集“AgoraClrLibrary.dll”或它的某一个依赖项
