### ISSUE TITLE
当我生成完成后，直接使用时就会报找不到dll

### ISSUE THREAD

**Issue by pengxiaobo123** [horsefaced/AgoraCLI#17]
static class Program
    {
        /// <summary>
        /// 应用程序的主入口点。
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());  //就是这句话报错。
        }
    }

System.IO.FileNotFoundException:“未能加载文件或程序集“AgoraClrLibrary.dll”或它的某一个依赖项。找不到指定的模块。”

**Comment by horsefaced** [comment]
你没把声网的dll放进去

发自我的 iPhone

**Comment by magikk** [comment]
初始化的时候提示agora initialize result is 0
 是不是表示注册失败了，大神

**Comment by horsefaced** [comment]
声望的接口返回值为0的一般是成功，非零的才是失败
