### ISSUE TITLE
枚举设备列表BUG

### ISSUE THREAD

**Issue by sxbjy** [horsefaced/AgoraCLI#18]
您好枚举视频设备列表的getDevice方法的deviceName和deviceId参数应该输出参数，音频设备也是同样。

**Comment by sxbjy** [comment]
目前自己实现了，但是切换摄像头时会有大概率出现错误。实现点如下：
int AgoraClrLibrary::ClrAudioDeviceCollection::getDevice(int index, String^% deviceName, String^% deviceId)
{

	char deviceNameBuf[MAX_DEVICE_ID_LENGTH] = { 0 };
	char deviceIdBuf[MAX_DEVICE_ID_LENGTH] = { 0 };
	int res = raw->getDevice(index, deviceNameBuf, deviceIdBuf);

	if (res != 0)
		return res;

	deviceName = toTString(deviceNameBuf);
	deviceId = toTString(deviceIdBuf);
	return res;
}；
其中 toTString方法
System::String^ toTString(const char* szStr)
{
	if (szStr == nullptr)
		return nullptr;
#ifdef UNICODE
	std::string str = szStr;
	try
	{
		return gcnew String(s2ws(str).c_str());
	}
	catch (const std::exception&)
	{
		return "s2ws exception";
	}
#else
	return gcnew String(szStr);
#endif
}

使用ClrAudioDeviceCollection对象时大概率出现错误，错误提示：System.NotImplementedException:“未实现该方法或操作。”

**Comment by horsefaced** [comment]
对，这个我实现的BUG，看API文档时没有注意到是返回参数。

**Comment by horsefaced** [comment]
请问System.NotImplementedException 这个异常出现在哪个语句里？还是出现在声网的API里面了？

**Comment by sxbjy** [comment]
AgoraClrLibrary::ClrAudioDeviceCollection::!ClrAudioDeviceCollection()
{
	throw gcnew System::NotImplementedException();
}
这个方法throw的异常

**Comment by horsefaced** [comment]
我去，居然还有这个问题，谢谢你啊，这个是我的疏忽了

**Comment by horsefaced** [comment]
已经修改好了。

**Comment by sxbjy** [comment]
十分感谢您的贡献

**Comment by sxbjy** [comment]
现在还有一个问题，就是获取到的deviceId 是空

**Comment by sxbjy** [comment]
AgoraClrVideoDeviceManager.cpp文件里面的第32行deviceName = gcnew String(deviceNameBuffer), deviceId = gcnew String(deviceId);  应该是你笔误写错了。deviceId = gcnew String(deviceIdBuffer);写成deviceId = gcnew String(deviceId);了

**Comment by horsefaced** [comment]
哈哈哈，谢谢。大清早写出来，脑子还没有清醒。

**Comment by sxbjy** [comment]
您好，调用 messageInstantSend(String account,int uid,String msg,String msgID); 方法发送点对点消息会立即触发连接丢失回调 (onReconnecting)和重连成功回调 (onReconnected)，这两个回调会不停触发。

**Comment by sxbjy** [comment]
经过调试，发现是因为消息内包含中文造成的。

**Comment by sxbjy** [comment]
接收到中文消息是乱码

**Comment by horsefaced** [comment]
哦，好的，我查看一下。

**Comment by horsefaced** [comment]
没有中文的话就不会有这种事情了吗？

**Comment by sxbjy** [comment]
没有中文没问题，发送消息包含中文就会停触发连接丢失回调 (onReconnecting)和重连成功回调 (onReconnected)

**Comment by horsefaced** [comment]
已经修改，如果还有问题，麻烦提新的issue，这个issue我先关闭了，因为后面这个messageInstantSend的问题与原来那个getDevice的问题无关

**Comment by tomato77** [comment]
请问，声网自动生成的AgoraSDK.log，咱们这里的demo ,怎么没有生成这个日志文件？
