### ISSUE TITLE
更新代码(修改信令中 messageInstantSend 方法不能处理中文的BUG)后信令无法登陆bug

### ISSUE THREAD

**Issue by sxbjy** [horsefaced/AgoraCLI#19]
1、StringToHGlobalAuto方法更改为StringToHGlobalAnsi后信令无法登陆，错误码206 （SignalingToken 无效）
2、int getEffectsVolume();
		int setEffectsVolume(int volume);
		int setVolumeOfEffect(int soundId, int volume);
		int playEffect(int soundId, String^ file, int loopCount, double pitch, double pan, int gain, bool publish);
		int stopEffect(int soundId);
		int stopAllEffects();
		int preloadEffect(int soundId, String^ file);
		int unloadEffect(int soundId);
		int pauseEffect(int soundId);
		int pauseAllEffects();
		int resumeEffect(int soundId);
		int resumeAllEffects();
这些方法没有实现。

**Comment by sxbjy** [comment]
仅仅对消息内容使用 StringToHGlobalAuto 客户端收到的消息内容丢失

**Comment by horsefaced** [comment]
第一个问题没有看懂哦，1、StringToHGlobalAuto方法更改为StringToHGlobalAnsi后信令无法登陆，错误码206 （SignalingToken 无效）
第二个，信令好久没更新了，哈哈哈哈，以前是因为他还没有出正式版本，现在应该是正式的了吧？

**Comment by horsefaced** [comment]
仅仅对消息内容使用 StringToHGlobalAuto 客户端收到的消息内容丢失 是丢失什么内容，能不能把具体情况发来我看一下

**Comment by sxbjy** [comment]
抱歉啊，我不会C++,经过昨天的不断测试，最开始你的这个方法没有问题，static std::string MarshalString(String ^s) {
		if (s == nullptr) return std::string();
		IntPtr middleStr = Runtime::InteropServices::Marshal::StringToHGlobalAnsi(s);
		std::string result((char *)middleStr.ToPointer());
		Runtime::InteropServices::Marshal::FreeHGlobal(middleStr);
		return result;
	} 。我发送消息时把消息内容先编码成UTF-8格式在发送就ok了，接收到消息也是先用这样处理。
var bytes = Encoding.Default.GetBytes(str);
                return Encoding.UTF8.GetString(bytes);

**Comment by sxbjy** [comment]
再次感谢你。

**Comment by horsefaced** [comment]
我知道了，我改成StringToHGlobalUni应该会比较好。这样子就不需要在转换了，反正现在基本都是UTF8了。

**Comment by horsefaced** [comment]
对了，你用的是那个分支？master还是2.2？

**Comment by horsefaced** [comment]
你后面说的方法都在2.2这个分支里了

**Comment by horsefaced** [comment]
我知道了，分支代码没有管理好造成的，我这就修改一下

**Comment by tomato77** [comment]
仅仅对消息内容使用 StringToHGlobalAuto, 客户端收到的消息内容丢失 ,比如发送aaa,接收到a;并且传中文接收到的是乱码

**Comment by tomato77** [comment]
我用的2.1 版本

**Comment by tomato77** [comment]
void AgoraClrLibrary::AgoraClrSignal::messageChannelSend(String^ channel, String ^ msg, String ^ msgID)
{
	std::string channelStr = MarshalString(channel), msgidStr = MarshalString(msgID), msgStr = MarshalString2(msg);
	signal->messageChannelSend(channelStr.c_str(), channelStr.length(), msgStr.c_str(), msgStr.length(), msgidStr.c_str(), msgidStr.length());
}

**Comment by horsefaced** [comment]
我知道了，已经修改发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] 更新代码(修改信令中 messageInstantSend 方法不能处理中文的BUG)后信令无法登陆bug (#19)发件人：tomato77 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,State change void AgoraClrLibrary::AgoraClrSignal::messageChannelSend(String^ channel, String ^ msg, String ^ msgID)
{
std::string channelStr = MarshalString(channel), msgidStr = MarshalString(msgID), msgStr = MarshalString2(msg);
signal->messageChannelSend(channelStr.c_str(), channelStr.length(), msgStr.c_str(), msgStr.length(), msgidStr.c_str(), msgidStr.length());
}

**Comment by tomato77** [comment]
怎么修改啊

**Comment by horsefaced** [comment]
你更新2.1的分支代码就可以了发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] 更新代码(修改信令中 messageInstantSend 方法不能处理中文的BUG)后信令无法登陆bug (#19)发件人：tomato77 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,State change 怎么修改啊

**Comment by tomato77** [comment]
2.1 分支代码， 登录206 token 无效    token   我传的“_no_need_token”

**Comment by tomato77** [comment]
我在原来的基础上，做一个utf8 的编码解码就可以了
static std::string gbkToutf8(const char *gbk)
	{
		std::string str;

		if (gbk != NULL)
		{
			int len = MultiByteToWideChar(936, 0, gbk, -1, NULL, 0);
			std::wstring strW;

			strW.resize(len);

			MultiByteToWideChar(936, 0, gbk, -1, (LPWSTR)strW.data(), len);

			len = WideCharToMultiByte(CP_UTF8, 0, strW.data(), len - 1, NULL, 0, NULL, NULL);

			str.resize(len);

			WideCharToMultiByte(CP_UTF8, 0, strW.data(), -1, (LPSTR)str.data(), len, NULL, NULL);
		}

		return str;
	}

	static std::string utf8Togbk(const char *utf8)
	{
		std::string str;

		if (utf8 != NULL)
		{
			int len = MultiByteToWideChar(CP_UTF8, 0, utf8, -1, NULL, 0);
			std::wstring strW;

			strW.resize(len);

			MultiByteToWideChar(CP_UTF8, 0, utf8, -1, (LPWSTR)strW.data(), len);

			len = WideCharToMultiByte(936, 0, strW.data(), len - 1, NULL, 0, NULL, NULL);

			str.resize(len);

			WideCharToMultiByte(936, 0, strW.data(), -1, (LPSTR)str.data(), len, NULL, NULL);
		}
		return str;
	}

**Comment by tomato77** [comment]
登录 、发送、接收 分别做编码 解码：
void AgoraClrLibrary::AgoraClrSignal::messageChannelSend(String^ channel, String ^ msg, String ^ msgID)
{
	std::string channelStr = MarshalString(channel), msgidStr = MarshalString(msgID), msgStr = MarshalString(msg);
	//signal->messageChannelSend(channelStr.c_str(), channelStr.length(), msgStr.c_str(), msgStr.length(), msgidStr.c_str(), msgidStr.length());
	signal->messageChannelSend(gbkToutf8(channelStr.c_str()).data(), gbkToutf8(channelStr.c_str()).size(), gbkToutf8(msgStr.c_str()).data(), gbkToutf8(msgStr.c_str()).size(), gbkToutf8(msgidStr.c_str()).data(), gbkToutf8(msgidStr.c_str()).size());
}

void AgoraClrLibrary::AgoraClrSignal::NativeOnMessageChannelReceive(char const * channelID, size_t channelID_size, char const * account, size_t account_size, uint32_t uid, char const * msg, size_t msg_size)
{
	//if (onMessageChannelReceive) onMessageChannelReceive(gcnew String(channelID), gcnew String(account), uid, gcnew String(msg));
	if (onMessageChannelReceive) onMessageChannelReceive(gcnew String(utf8Togbk(channelID).c_str()), gcnew String(utf8Togbk(account).c_str()), uid, gcnew String(utf8Togbk(msg).c_str()));
}

**Comment by horsefaced** [comment]
你没有更新我的2.1分支代码吧？发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] 更新代码(修改信令中 messageInstantSend 方法不能处理中文的BUG)后信令无法登陆bug (#19)发件人：tomato77 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,State change 登录 、发送、接收 分别做编码 解码：

void AgoraClrLibrary::AgoraClrSignal::messageChannelSend(String^ channel, String ^ msg, String ^ msgID)

{

std::string channelStr = MarshalString(channel), msgidStr = MarshalString(msgID), msgStr = MarshalString(msg);

//signal->messageChannelSend(channelStr.c_str(), channelStr.length(), msgStr.c_str(), msgStr.length(), msgidStr.c_str(), msgidStr.length());

signal->messageChannelSend(gbkToutf8(channelStr.c_str()).data(), gbkToutf8(channelStr.c_str()).size(), gbkToutf8(msgStr.c_str()).data(), gbkToutf8(msgStr.c_str()).size(), gbkToutf8(msgidStr.c_str()).data(), gbkToutf8(msgidStr.c_str()).size());

}

void AgoraClrLibrary::AgoraClrSignal::NativeOnMessageChannelReceive(char const * channelID, size_t channelID_size, char const * account, size_t account_size, uint32_t uid, char const * msg, size_t msg_size)

{

//if (onMessageChannelReceive) onMessageChannelReceive(gcnew String(channelID), gcnew String(account), uid, gcnew String(msg));

if (onMessageChannelReceive) onMessageChannelReceive(gcnew String(utf8Togbk(channelID).c_str()), gcnew String(utf8Togbk(account).c_str()), uid, gcnew String(utf8Togbk(msg).c_str()));

}

**Comment by tomato77** [comment]
2.1分支代码 我更新了一下，在我本地运行，登录 ，加入频道 打开摄像头都没反应，然后我就继续在没更新之前的代码上改的。。。可能和我VS 版本不兼容吗，
agora initialize result is -101
agora setuplocalVideo result is -7
agora enableVideo result is -7
agora startPreview result is -7
agora 206登录失败 result is 0
agora join channel result is -7

**Comment by horsefaced** [comment]
你要把AppID换成你自己的发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] 更新代码(修改信令中 messageInstantSend 方法不能处理中文的BUG)后信令无法登陆bug (#19)发件人：tomato77 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,State change 2.1分支代码 我更新了一下，在我本地运行，登录 ，加入频道 打开摄像头都没反应，然后我就继续在没更新之前的代码上改的。。。可能和我VS 版本不兼容吗，

agora initialize result is -101

agora setuplocalVideo result is -7

agora enableVideo result is -7

agora startPreview result is -7

agora 206登录失败 result is 0

agora join channel result is -7
