### ISSUE TITLE
关于通信和直播的区别

### ISSUE THREAD

**Issue by wx919** [horsefaced/AgoraCLI#2]
你好，看你的demo能加入频道成功，请问你的api中对于通信和直播有区分吗？

使用的都是AgoraClrLibrary.AgoraClr的initialize吗？

**Comment by horsefaced** [comment]
没有区分，其实主要是声网没有区分，只要模式改一下就行了。具体看声网的文档

**Comment by wx919** [comment]
是的，已经知道了，谢谢！

**Comment by horsefaced** [comment]
哇，不好意思，我这几天没有关注这里，你们是用什么工具还是怎么了，会这么快知道我回复了没有？

**Comment by wx919** [comment]
qq邮箱通知了。嘿嘿

**Comment by horsefaced** [comment]
原来我的邮箱把这个自动拉到垃圾邮件里去了

**Comment by wx919** [comment]
嘿嘿，大牛你的sdk已经被声网的工程师推荐了！
