### ISSUE TITLE
AgoraClrLibrary编译失败

### ISSUE THREAD

**Issue by huamao** [horsefaced/AgoraCLI#20]
我使用VS 2017，打开项目后，直接编译项目和AgoraClrLibrary都失败了，报了不少错误，如下：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0103	当前上下文中不存在名称“RenderMode”	AgoraClrDemo	D:\Projects2017\AgoraCLI-master\AgoraClrLibrary\AgoraClrDemo\Form1.cs	50	活动的
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2020	无法解析的标记(0600022F) AgoraClrLibrary.AgoraClr::getEffectsVolume	AgoraClrLibrary	D:\Projects2017\AgoraCLI-master\AgoraClrLibrary\AgoraClrLibrary\AgoraClrVideoDeviceManager.obj	1	
... ...

**Comment by horsefaced** [comment]
晕，我知道了，分支的代码乱了，我这就改正

**Comment by horsefaced** [comment]
已修改
