### ISSUE TITLE
setLiveTranscoding能否正常使用

### ISSUE THREAD

**Issue by opensourcegoo** [horsefaced/AgoraCLI#22]
旁路直播setLiveTranscoding这个功能是不是还不能使用 ，sdk版本2.1，目前无法正常旁路推流
int AgoraClrLibrary::AgoraClr::setLiveTranscoding(ClrLiveTranscoding ^ transcoding)
{
	LiveTranscoding lt;
	transcoding->writeRaw(lt);
	return rtcEngine->setLiveTranscoding(lt);
}

**Comment by horsefaced** [comment]
你可以试一下2.2版本

**Comment by opensourcegoo** [comment]
2.2版本Demo运
![1544078404 1](https://user-images.githubusercontent.com/44453361/49566231-ea6f2b00-f964-11e8-9fa9-2c6c883b8744.jpg)

**Comment by opensourcegoo** [comment]
![1544078404 1](https://user-images.githubusercontent.com/44453361/49566255-fd81fb00-f964-11e8-8895-f8922f384783.jpg)
大佬， 2.2版本demo运行时，初始化和加入频道都会报错，无法使用

**Comment by horsefaced** [comment]
这个是因为从2.2开始他们的认证改为token形式了，对了，推流要和他们的商务联系才有，所以我没有试过这个功能发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] setLiveTranscoding能否正常使用 (#22)发件人：opensourcegoo 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,Comment 

大佬， 2.2版本demo运行时，初始化和加入频道都会报错，无法使用

**Comment by opensourcegoo** [comment]
![image](https://user-images.githubusercontent.com/44453361/49572791-830ea680-f977-11e8-9b5c-39e2a40deb74.png)
我看下2.1和2.2的源码发现 setLiveTranscoding方法都是已经强行给了默认值，导致我们在使用旁路直播功能时设置推流传参数的时候设置的值是无效的，没法做修改

**Comment by horsefaced** [comment]
好，这个我查看一下发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] setLiveTranscoding能否正常使用 (#22)发件人：opensourcegoo 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,Comment 

我看下2.1和2.2的源码发现 setLiveTranscoding方法都是已经强行给了默认值，导致我们在使用旁路直播功能时设置推流传参数的时候设置的值是无效的，没法做修改

**Comment by opensourcegoo** [comment]
期待

**Comment by horsefaced** [comment]
我看了代码了，是没有问题的 setLiveTranscoding(ClrLiveTranscoding ^transcoding) 这里的你 new ClrLiveTranscoding() 后就可以设置它的内容，传进去后，会通过 writeRaw 写成C++的structure。

**Comment by opensourcegoo** [comment]
哦是的 抱歉是我没看清楚，但还有一个问题我在设置推流时传给setLiveTranscoding的 ClrLiveTranscoding这个类型参数中没有找到ClrTranscodingUser类型的属性，导致ClrLiveTranscoding和ClrTranscodingUser无法关联，声网官网提供的SDK示例说明需关联才能设置，我在你的ClrLiveTranscoding类型源码里面发现其实有这个名为transcodingUsers的属性，但是编译出来之后无法找到，反编译了一下，发现这个属性又是readonly的，反正无法使用，请大佬
![1001](https://user-images.githubusercontent.com/44453361/49632091-79e11080-fa2f-11e8-8b7a-468ec19e81a0.png)
![1002](https://user-images.githubusercontent.com/44453361/49632092-79e11080-fa2f-11e8-9fa5-a99488c9d005.png)
![1003](https://user-images.githubusercontent.com/44453361/49632094-79e11080-fa2f-11e8-8087-309c221c930d.png)


帮我看一下

**Comment by horsefaced** [comment]
好的，我晚上看一下发自我的华为手机

**Comment by opensourcegoo** [comment]
好的，谢谢大佬

**Comment by opensourcegoo** [comment]
我刚刚又调了一下，如果给ClrLiveTranscoding变量强行使用该属性 例如：config.transcodingUsers  vs提示"现用语言不支持 ClrTranscodingUser"，而不是报找不到该成员，我谷歌了一下，这样的问题指向的是visual C++部分，C++不是很懂, 搜索条件"is not supported by the language c++ cli"

**Comment by horsefaced** [comment]
我在2.1与2.2分支上进行了修改，你看看能不能用，谢谢你的反馈。

**Comment by opensourcegoo** [comment]
好的，大佬辛苦，周一




            
            
                
                    
                            
                                
                            
                            
                                卞云鹏
                            
                    
                        
                            
                                    邮箱：opensourcegoo@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年12月07日 20:48，horsefaced 写道： 我在2.1与2.2分支上进行了修改，你看看能不能用，谢谢你的反馈。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/horsefaced/AgoraCLI","title":"horsefaced/AgoraCLI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/horsefaced/AgoraCLI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@horsefaced in #22: 我在2.1与2.2分支上进行了修改，你看看能不能用，谢谢你的反馈。"}],"action":{"name":"View Issue","url":"https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-445223017"}}}

[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-445223017",
"url": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-445223017",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [horsefaced/AgoraCLI] setLiveTranscoding能否正常使用 (#22)",
"sections": [
{
"text": "",
"activityTitle": "**horsefaced**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@horsefaced",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"horsefaced/AgoraCLI\",\n\"issueId\": 22,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"horsefaced/AgoraCLI\",\n\"issueId\": 22\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-445223017"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 420012794\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by opensourcegoo** [comment]
你好，今天我用了ClrTranscodingUser属性已经可以使用了，但是旁路推流依然还有问题。
在调用完addPublishStreamUrl设置推流之后  旁路回调函数 onStreamPublished事件中竟然回调执行了两次，第一次返回的参数(第二个)值为0，然后又莫名的再返回了一次 参数值为1，Agora SDK中描述 0为正常，1为 “一般性的错误（没有明确归类的错误原因）”，正常应该回调一次。
还有就是如果再次启动程序第二次调用addPublishStreamUrl 直接返回状态值19(19 代表"资源已被占用，不能重复使用"),这一次只回调一次，再次启动程序就是这样的问题一直循环   
由于不会没有用您所说2.2  token认证形式， 所以 使用的版本是一直是2.1， 希望大佬能帮看看将旁路直播打通，附上我的代码
![image](https://user-images.githubusercontent.com/44453361/49722708-4fe25500-fca0-11e8-8b5b-59b4bc0eeebb.png)

![2o 0cv sf364k8yl dh75 3](https://user-images.githubusercontent.com/44453361/49722734-5f619e00-fca0-11e8-92e3-785a03f98356.png)

**Comment by opensourcegoo** [comment]
互动直播是没有问题的，就是卡在旁路直播这里

**Comment by horsefaced** [comment]
请先确认一下，API调用说明上 addPublishStreamUrl 是需要在 
> 请确保在成功加入房间后才能调用该接口。
> 该方法每次只能增加一路 CDN 推流地址。若需推送多路流，则需多次调用该方法。
> url 不支持中文字符等特殊字符。

addPublishStreamUrl之后是要removePublishStreamUrl的
而且setLiveTranscoding本身也是需要确认成功

> 主播转码更新回调 (onTranscodingUpdated)

**Comment by opensourcegoo** [comment]
旁路可以使用了，非常感谢大佬的指点！，现在又遇到一个问题就是agora对象最后析构时执行 agora.release();这句导致程序直接退出 C++运行报错信息(-1073741819 (0xc0000005) 'Access violation')。您的2.1demo上点击测试按钮也是这样，最新的2.2版本demo则没有，您已经修复了， 由于我不会做您所说的token认证形式( 老式的初始化和joinchannel还是都可以用的),所以现在只能用2.1，求大佬能不能把2.2上完善的功能加到2.1上，相当于出两个版本(token与非token认证)都可以使用，再次感谢大佬!

**Comment by horsefaced** [comment]
好，我晚上看看发自我的华为手机-------- 原始邮件 --------主题：Re: [horsefaced/AgoraCLI] setLiveTranscoding能否正常使用 (#22)发件人：opensourcegoo 收件人：horsefaced/AgoraCLI 抄送：horsefaced ,Mention 旁路可以使用了，非常感谢大佬的指点！，现在又遇到一个问题就是agora对象最后析构时执行 agora.release();这句导致程序直接退出 C++运行报错信息(-1073741819 (0xc0000005) 'Access violation')。您的2.1demo上点击测试按钮也是这样，最新的2.2版本demo则没有，您已经修复了， 由于我不会做您所说的token认证形式( 老式的初始化和joinchannel还是都可以用的),所以现在只能用2.1，求大佬能不能把2.2上完善的功能加到2.1上，相当于出两个版本(token与非token认证)都可以使用，再次感谢大佬!

**Comment by horsefaced** [comment]
挺遗憾的告诉你，2.1与2.2的release是完全一样的代码，一般在程序关掉时才release，但程序一旦关掉，Windows会自动处理资源的问题，所以推荐你就不要调用这个代码吧。

**Comment by opensourcegoo** [comment]
您的意思是说这个对象就不让它释放了，我这边的业务逻辑是关闭直播但是程序依然在运行，用户依然可以继续重新开播，不知道这样持续开播对象一直不释放会不会有问题，既然2.1和2.2的代码一样可是demo跑起来调用release结果一个不崩溃一个崩溃，这个就很疑惑了




            
            
                
                    
                            
                                
                            
                            
                                卞云鹏
                            
                    
                        
                            
                                    邮箱：opensourcegoo@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年12月12日 21:16，horsefaced 写道： 挺遗憾的告诉你，2.1与2.2的release是完全一样的代码，一般在程序关掉时才release，但程序一旦关掉，Windows会自动处理资源的问题，所以推荐你就不要调用这个代码吧。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/horsefaced/AgoraCLI","title":"horsefaced/AgoraCLI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/horsefaced/AgoraCLI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@horsefaced in #22: 挺遗憾的告诉你，2.1与2.2的release是完全一样的代码，一般在程序关掉时才release，但程序一旦关掉，Windows会自动处理资源的问题，所以推荐你就不要调用这个代码吧。"}],"action":{"name":"View Issue","url":"https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446584451"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446584451",
"url": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446584451",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by opensourcegoo** [comment]
可能是我表达不够清楚吧，您的github上的2.1的winform的示例程序点击测试即调用release方法后程序会异常退出程序，报错信息：-1073741819 (0xc0000005) 'Access violation')。2.2的示例程序则没有问题




            
            
                
                    
                            
                                
                            
                            
                                卞云鹏
                            
                    
                        
                            
                                    邮箱：opensourcegoo@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年12月12日 21:27，opensourcegoo 写道： 
您的意思是说这个对象就不让它释放了，我这边的业务逻辑是关闭直播但是程序依然在运行，用户依然可以继续重新开播，不知道这样持续开播对象一直不释放会不会有问题，既然2.1和2.2的代码一样可是demo跑起来调用release结果一个不崩溃一个崩溃，这个就很疑惑了




            
            
                
                    
                            
                                
                            
                            
                                卞云鹏
                            
                    
                        
                            
                                    邮箱：opensourcegoo@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年12月12日 21:16，horsefaced 写道： 挺遗憾的告诉你，2.1与2.2的release是完全一样的代码，一般在程序关掉时才release，但程序一旦关掉，Windows会自动处理资源的问题，所以推荐你就不要调用这个代码吧。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/horsefaced/AgoraCLI","title":"horsefaced/AgoraCLI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/horsefaced/AgoraCLI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@horsefaced in #22: 挺遗憾的告诉你，2.1与2.2的release是完全一样的代码，一般在程序关掉时才release，但程序一旦关掉，Windows会自动处理资源的问题，所以推荐你就不要调用这个代码吧。"}],"action":{"name":"View Issue","url":"https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446584451"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446584451",
"url": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446584451",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by horsefaced** [comment]
关闭直播时，你把推流remove掉，把频道退掉，保留agora这个对象，下次进去时在复用时没有问题的。不一定要每次都new出来。等程序彻底关掉的时候，资源也就释放了。

**Comment by opensourcegoo** [comment]
好的，我明天会按您的方式来做，非常感谢！




            
            
                
                    
                            
                                
                            
                            
                                卞云鹏
                            
                    
                        
                            
                                    邮箱：opensourcegoo@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年12月12日 21:41，horsefaced 写道： 关闭直播时，你把推流remove掉，把频道退掉，保留agora这个对象，下次进去时在复用时没有问题的。不一定要每次都new出来。等程序彻底关掉的时候，资源也就释放了。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/horsefaced/AgoraCLI","title":"horsefaced/AgoraCLI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/horsefaced/AgoraCLI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@horsefaced in #22: 关闭直播时，你把推流remove掉，把频道退掉，保留agora这个对象，下次进去时在复用时没有问题的。不一定要每次都new出来。等程序彻底关掉的时候，资源也就释放了。"}],"action":{"name":"View Issue","url":"https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446591461"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446591461",
"url": "https://github.com/horsefaced/AgoraCLI/issues/22#issuecomment-446591461",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by horsefaced** [comment]
结果如何

**Comment by opensourcegoo** [comment]
您好，抱歉现在才看到，可以使用了，非常感谢大佬的指点，同时之前突然不能用的老版声网也可以用了，他们估计也做了修改




            
            
                
                    
                            
                                
                            
                            
                                卞云鹏
                            
                    
                        
                            
                                    邮箱：opensourcegoo@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年12月20日 06:40，horsefaced 写道： Closed #22.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/horsefaced/AgoraCLI","title":"horsefaced/AgoraCLI","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/horsefaced/AgoraCLI"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #22."}],"action":{"name":"View Issue","url":"https://github.com/horsefaced/AgoraCLI/issues/22#event-2036974693"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/horsefaced/AgoraCLI/issues/22#event-2036974693",
"url": "https://github.com/horsefaced/AgoraCLI/issues/22#event-2036974693",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shidawei19760823** [comment]
@opensourcegoo ，你好，我们也碰到旁路推流失败的问题，请问你最后怎么解决的？如果可以，加个QQ？2913737708，谢谢
