### ISSUE TITLE
setLiveTranscoding 和 addPublishStreamUrl 是否还能使用？

### ISSUE THREAD

**Issue by unbearable** [horsefaced/AgoraCLI#23]
不好意思 我下载的是您当前的最新的版本 我有看到之前的人提问的 但是也是没有解决旁路推流的问题 声网提供的DEMO里头 旁路推流setLiveTranscoding没有onTranscodingUpdated的回调 所以我没法知道我有没有设置成功 然后Publish也没有回调 因为说是不管怎么样addPublish返回的都是0 所以我想问下您  appId已经找客服开通过了 用他们提供的C++是旁路推流成功了  c#这个就是没有成功  是什么原因呢  您能看下么

**Comment by horsefaced** [comment]
OK，我看看

**Comment by horsefaced** [comment]
我看了一下2.3的代码，是有onTranscodingUpdated这个方法，setLiveTranscoding这个方法返回的结果是什么？因为我这边没有旁路推流的权限，所以这个其实我没有测试过的。

**Comment by unbearable** [comment]
放回的结果都是0   后面我看了下日志   setLiveTranscoding这个方法应该是通过了  但是addPublish的日志提示一直是说因为加密了  所以一直没有成功   但是我并没有加密所以不知道为什么   所以您知道c++那边有哪里有调用加密的么？

**Comment by horsefaced** [comment]
怎么关闭了？问题解决了吗？

**Comment by shidawei19760823** [comment]
@horsefaced ，请问有QQ吗？我这边也碰到推流推不出去的问题， QQ里聊，可以吗？2913737708

**Comment by opensourcegoo** [comment]
你好 你有什么问题抱歉刚看到

**Comment by opensourcegoo** [comment]
@shidawei19760823  你好 你有什么问题抱歉刚看到
