### ISSUE TITLE
能够支持音频互动直播吗

### ISSUE THREAD

**Issue by opensourcegoo** [horsefaced/AgoraCLI#24]
大佬您好，我又来请教下了，目前封的dll 能够支持声网音频互动直播功能吗

**Comment by horsefaced** [comment]
这个我还不知道呢，因为我封的很薄一层，Windows的dll能支持的功能，我应该都支持了，你试试。

**Comment by opensourcegoo** [comment]
嗯，还有个事情，就是新的demo里不再使用appid验证，而是用token形式，因为没有这个概念不会写这块验证方式，从2.2开始就无法再使用您封的新的sdk，可以求一个以令牌形式访问的demo吗？想知道怎么写的(或者给个思路也行)，这样能够跟上您的最新版本
