### ISSUE TITLE
MarshalString: String^  =>  std::string  封装新的 函数

### ISSUE THREAD

**Issue by xifarm** [horsefaced/AgoraCLI#27]
我的环境：

- SDK 2.9
- Visual Studio 2019 (v142)
- X64 Debug

**String^  =>  std::string**

\AgoraClrLibrary.h  中原函数：MarshalString
我传入的AppID，仅仅返回了第一个字符，导致初始化失败。

我重新封装了一下，好使了，分享代码如下：

`
#include <msclr\marshal_cppstd.h>
using namespace msclr::interop;

	static std::string MarshalString1(String^ s) {
		if (s == nullptr) return std::string();

		marshal_context^ context = gcnew marshal_context();
		const char* name1 = context->marshal_as<const char*>(s);

		char* pch = _strdup(name1); //const char* => char*
		delete context;  

		return std::string(pch);
	}
`

**Comment by horsefaced** [comment]
谢谢支持，我看到你问的2.9分支了，这个分支我只是暂时创建，还没开始移植，计划是这个中秋进行。推荐暂时先不要使用。

**Comment by xifarm** [comment]
> 谢谢支持，我看到你问的2.9分支了，这个分支我只是暂时创建，还没开始移植，计划是这个中秋进行。推荐暂时先不要使用。

请问使用哪个分支比较好一些？

我国庆节前需要封装一个WPF（C#）的应用demo呢。
