### ISSUE TITLE
C# WPF视频渲染流程请教

### ISSUE THREAD

**Issue by xifarm** [horsefaced/AgoraCLI#28]
大家好，请教一下WPF (C#)里面视频渲染的流程。

我们需要在一个Window窗体显示10个Video视频，所以WPF通过Handle给C++传递方案不行，只能获得VideoFrame进行自己渲染。

现在的视频流程：

1. C++提供YUV420 （C++ CLR封装）
2. C# 进行YUV420转换RGBA
3. C#进行bitmap write --> 显示到WPF  Image上。

问题是，CPU、Memory、GPU比较费，几个视频都是720P情况下，明显的卡顿现象。

不知道大家有无好的办法。

**Comment by 836257514** [comment]
我有办法，你不要在memory和gpu memory里倒来倒去就会快了，硬解码之后直接刷在d3dimage里
