### ISSUE TITLE
wpf集成

### ISSUE THREAD

**Issue by lauix** [horsefaced/AgoraCLI#3]
wpf项目中集成AgoraClrLibrary.dll后，并将agorartc.dll，AgoraRTCEngine.dll和agorasdk.dll复制到输出目录，在开发机上可以正常运行，但是把应用复制到其它机器上就报找不到AgoraClrLibrary.dll或依赖的项。编译Release版也不行。后来发现只要安装vs2015后，就没有问题了。这是怎么回事呢。

**Comment by horsefaced** [comment]
visual studio的用于发布的C++运行时你有装吗?

**Comment by lauix** [comment]
是 Visual C++ Redistributable for Visual Studio 2015  吗

**Comment by lauix** [comment]
解决了，是少了这个运行时。

**Comment by horsefaced** [comment]
解决了就好
