### ISSUE TITLE
为什么编译成功，总是提示dll找不到

### ISSUE THREAD

**Issue by andisk** [horsefaced/AgoraCLI#30]
![image](https://user-images.githubusercontent.com/52537788/70232413-5d3cfd00-1797-11ea-8dd5-3b9c7922d34e.png)

然后目录里没有

![image](https://user-images.githubusercontent.com/52537788/70232509-8fe6f580-1797-11ea-8110-5f54fd4add13.png)

运行demo，会提示找不到的错误
![image](https://user-images.githubusercontent.com/52537788/70232563-b147e180-1797-11ea-8ca6-640dfccb5656.png)

我查了demo里对dll的引用路径也是对的，但是就是报错
我用vs2017，编译的2.2版本，当然我也编译过2.3版本。用2019也编译过master的最新版本，都是这个问题？为什么会这样，难道就是我一个人有疑问吗？

**Comment by horsefaced** [comment]
要把agora的dll也拷贝的这个目录下

发自我的iPhone

**Comment by WayneShao** [comment]
是测了下，需要用x86版本的dll

**Comment by hello7bb** [comment]
这个报错我通过引用了\Agora_Native_SDK_for_Windows_FULL\libs\x86的agora_rtc_sdk.dll得到解决.

但是又遇到了集“AgoraClrRTMLibrary.dll”或它的某一个依赖项。找不到指定的模块。”文件报错.
