### ISSUE TITLE
无法实现推流到移动端

### ISSUE THREAD

**Issue by idadawn** [horsefaced/AgoraCLI#33]
桌面共享和视频信息无法推送到移动端

**Comment by genMY** [comment]
![image](https://user-images.githubusercontent.com/17629591/76861105-04e9c100-6897-11ea-8c60-74fd6b7b1e35.png)
删除掉registerPacketObserver 代码就可以了

**Comment by horsefaced** [comment]
master和2.9分支都进行了修改, 推荐升级试试.

**Comment by idadawn** [comment]
ok&nbsp;是的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨尚彬"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 晚上9:34
收件人: "horsefaced/AgoraCLI"<AgoraCLI@noreply.github.com&gt;; 
抄送: "Dawn"<ida.dawn@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [horsefaced/AgoraCLI] 无法实现推流到移动端 (#33)





 

 删除掉registerPacketObserver 代码就可以了

**Comment by idadawn** [comment]
好的 谢谢 昨天问了声网的人 也是这么修改 非常好用 感谢
