### ISSUE TITLE
在发布正式环境的时候出现白屏

### ISSUE THREAD

**Issue by idadawn** [horsefaced/AgoraCLI#35]
我是用winform 的方式进行调用的 ，现在在发布到正式用户机器上无法正常使用
应用程序: AgoraClrDemo.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.IO.FileNotFoundException
   在 AgoraClrDemo.Form1..ctor()
   在 AgoraClrDemo.Program.Main()

错误应用程序名称: AgoraClrDemo.exe，版本: 1.0.0.0，时间戳: 0x5e81fac8
错误模块名称: KERNELBASE.dll，版本: 10.0.18362.145，时间戳: 0xf5733ace
异常代码: 0xe0434352
错误偏移量: 0x001133d2
错误进程 ID: 0x1d9c
错误应用程序启动时间: 0x01d6081a52948d66
错误应用程序路径: C:\Users\DawnLee\Desktop\Debug - 副本\AgoraClrDemo.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: f4157e78-7149-4d92-b0bb-c942e586156c
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by horsefaced** [comment]
你开发的机子是好的嘛？是好的话看看你有没有把所有的依赖dll都打包进去，还有客户那边的平台是否安装对了。

发自我的iPhone

**Comment by idadawn** [comment]
开发机器是正常的  dll 都打包进去了 
方便的话 发一下我的邮箱吧ida.dawn@qq.com吧
