### ISSUE TITLE
三个dll文件无法直接引用

### ISSUE THREAD

**Issue by lao809188779** [horsefaced/AgoraCLI#4]
现在可以添加AgoraClrLibrary.dll这个文件的引用，但是声网的初始化还要有agorartc.dll AgoraRTCEngine.dll agorasdk.dll 这三个文件，但是这三个文件引用的时候显示的是文件不是有效的程序集，只能在编译完之后将这三个文件copy到输出目录才能正常运行， 否则会出现未能加载文件或程序集 “AgoraClrLibrary.dll”或它的某一个依赖项，请问这个怎么解决。

**Comment by horsefaced** [comment]
这三个文件其实是声网用C++直接写的dll，不是.net程序集的一部分，所以只能进行copy。

**Comment by lao809188779** [comment]
那我想打包成安装包怎么弄

**Comment by horsefaced** [comment]
具体要看你用的什么打包程序了，一般都是可以指定要打进什么文件的。

**Comment by lao809188779** [comment]
感觉光打包进去没用   直接安装好之后把dll的文件copy进去就还是缺少依赖项    就只有在debug的时候成功了

**Comment by horsefaced** [comment]
只有在debug成功的话，你有编译成release吗？

**Comment by lao809188779** [comment]
没有试过  明天试试

**Comment by lao809188779** [comment]
一样   VS中可以直接启动    但是把Release文件拷给别人     其他页面可以   一旦涉及声网的dll就缺少依赖项

**Comment by horsefaced** [comment]
你是不是没有在别人机子上装Visual C++ Redistributable for Visual Studio

**Comment by lao809188779** [comment]
没有啊    给用户装的话用户不会装这些东西吧

**Comment by horsefaced** [comment]
这个一定要装，你可以打成安装包自动去装，就像自动安装.net框架一样，要不然vc++的程序是运行不了的。

**Comment by lao809188779** [comment]
我试试

**Comment by lao809188779** [comment]
我在打包的系统组件中勾了visual C++"14" Runtime Libraries（ARM），  visual C++"14" Runtime Libraries（ARM），  visual C++"14" Runtime Libraries（ARM）三个组件还是老样子

**Comment by lao809188779** [comment]
我在打包的系统组件中勾了visual C++"14" Runtime Libraries（ARM）， visual C++"14" Runtime Libraries（X86）， visual C++"14" Runtime Libraries（X64）三个组件还是老样子

**Comment by horsefaced** [comment]
这方面我不是很清楚，你最好上网查一下如何把Visual C++ Redistributable for Visual Studio给打包进去。还有，确认是不是这个问题的最方便的方法就是 https://github.com/horsefaced/AgoraCLI/issues/3 参考一下是不是这个情况。

**Comment by lao809188779** [comment]
另一台电脑也装了这个，Visual C++ Redistributable 怎么办

**Comment by horsefaced** [comment]
什么？没有明白啊
