### ISSUE TITLE
你好，请问为何使用APPID引擎初始化会失败？

### ISSUE THREAD

**Issue by LZD121** [horsefaced/AgoraCLI#42]
![image](https://user-images.githubusercontent.com/59716053/88023899-6e8b1c00-cb64-11ea-84b9-bf0aca144b16.png)
返回-101 初始化失败

望大佬回复

**Comment by horsefaced** [comment]
ERR_INVALID_APP_ID 	
101: 不是有效的 App ID。请更换有效的 App ID 重新加入频道。
你看一下你用了什么AppID, 是否有效, 不要用我提供的AppID, 那个可能已经失效了.

**Comment by LZD121** [comment]
好的，感谢大佬，最后发现是公司的网络把声网的端口给禁了导致失败
另外请问一下sdk里的agora_sig_sdk.dll是在声网官网哪里能找到下载的？一直找不到

**Comment by horsefaced** [comment]
信令SDK应该已经不支持了, 推荐你转到最新的版本上来.
