### ISSUE TITLE
uid越界超过int.max最大值,会变成负数的问题

### ISSUE THREAD

**Issue by hello7bb** [horsefaced/AgoraCLI#43]
加入频道之后触发onJoinChannelSuccess的事件,uid会存在负数的情况

目前发现是这个uid大于int.max时,就会变成负数..

**Comment by horsefaced** [comment]
int.max是个非常大的数, 推测是有频繁加入频道的情况, 你看看你那边的代码调用情况.



在 2020-08-05 12:05:26，"hello7bb" <notifications@github.com> 写道：

加入频道之后触发onJoinChannelSuccess的事件,uid会存在负数的情况

目前发现是这个uid大于int.max时,就会变成负数..

**Comment by hello7bb** [comment]
这个后续我自己这边找到了问题点
C#的int范围 是 -2^31到2^31 最大值为2,147,483,648
而Agora官方文档给出的uid为string,取值范围1~ 2^32-1 在C#中int的取值范围的之外的.
所以当uid的取值范围在2^31~2^32-1,之间时会变为负数.


实际上C#int为带有符号的整形.所表示的数格式是与Agora官方uid的方位个数是一致的.
可以采用下述方式,判断如果uid已经小于0时,通过下述简单计算可以得到准确uid
int dt = uid - int.MinValue + 1;
long ruid = (long)dt + (long)int.MaxValue;

往horsefaced可以在后续版本中,考虑是否调整.

可以考虑在共用代码中做一下调整

**Comment by hello7bb** [comment]
> int.max是个非常大的数, 推测是有频繁加入频道的情况, 你看看你那边的代码调用情况.
> 
> 
> 
> 在 2020-08-05 12:05:26，"hello7bb" <notifications@github.com> 写道：
> 
> 加入频道之后触发onJoinChannelSuccess的事件,uid会存在负数的情况
> 
> 目前发现是这个uid大于int.max时,就会变成负数..
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
这个后续我自己这边找到了问题点
C#的int范围 是 -2^31到2^31 最大值为2,147,483,648
而Agora官方文档给出的uid为string,取值范围1~ 2^32-1 在C#中int的取值范围的之外的.
所以当uid的取值范围在2^31~2^32-1,之间时会变为负数.
实际上C#int为带有符号的整形.所表示的数格式是与Agora官方uid的方位个数是一致的.
可以采用下述方式,判断如果uid已经小于0时,通过下述简单计算可以得到准确uid
int dt = uid - int.MinValue + 1;
long ruid = (long)dt + (long)int.MaxValue;
往horsefaced可以在后续版本中,考虑是否调整.
可以考虑在共用代码中做一下调整

**Comment by horsefaced** [comment]
了解了, OK, 我会对其进行修改, agora内部应该是使用uint来表示uid. 谢谢你的帮助

**Comment by horsefaced** [comment]
你是用那个版本的?

**Comment by hello7bb** [comment]
8 Jun 2020 10:33  Merge pull request #39 from wulao /3.0 这个
