### ISSUE TITLE
請問要如何監聽 RTM 的 事件

### ISSUE THREAD

**Issue by shawn-liao** [horsefaced/AgoraCLI#44]
使用 Agora，只要加入底下一行，就可以成功監聽 onUserJoined 事件
agora.onUserJoined += new AgoraClrLibrary.onUserJoined(OnUserJoined);

但是使用 RTM 時，我要監聽 onMemberJoined 事件，不過這邊我就不會使用了
AgoraClrRTMChannel room = agoraRTM.createChannel(1234);
room.onMemberJoined += new AgoraClrRTMLibrary.AT<AgoraClrRTMLibrary::ClrChannelMember ^>.Type  <---這邊出現紅字，編譯不過

請問能給個監聽RTM事件的範例嗎，非常謝謝

**Comment by horsefaced** [comment]
```c# 
AgoraClrRTMChannel channel = agoraRTM.createChannel("1234");
channel.onMemberJoined += onMemberJoined;

private void onMemberJoined(ClrChannelMember member)
 {

 }
```

其实那些事件的类型转换是不必要的。比如
```c#
            agora.onCameraReady += onCameraReady;
            agora.onJoinChannelSuccess += onJoinChannelSuccess;
            agora.onFirstRemoteVideoDecoded += onFirstRemoteVideoDecoded;
            agora.onFirstLocalVideoFrame += onFirstLocalVideoFrame;
            agora.onCaptureVideoFrame += onCaptureVideoFrame;
            agora.onPreEncodeVideoFrame += onPreEncodeVideoFrame;
```
这样子也是可以的。

**Comment by shawn-liao** [comment]
謝謝，我明白了，
現在可以監聽事件了。
我關閉 issue.
