### ISSUE TITLE
本地开发环境可以，用户的别的电脑就不行

### ISSUE THREAD

**Issue by Kipiqid** [horsefaced/AgoraCLI#48]
不知道是因为缺少环境还是什么原因，我把打包好的应用程序在我本机运行就可以，其他电脑也只有一台可能运行，其余的电脑都会报错，"AgoraClrLibrary  试图加载格式不正确的程序“

**Comment by horsefaced** [comment]
这个问题很有可能是安装了和编译架构不一致的dll造成的

发自我的iPad

**Comment by Kipiqid** [comment]
我关注到你在readme中写到需要安装 Visual C++ Redistributable for Visual Studio 才能运行，因此我在想可不可能和本机某些运行时环境有关系呢？（我已经在测试电脑上安装了C++的运行时全家桶，依然不行，不知道是不是还缺少别的什么环境）毕竟我写的demo在本机可以，原封不动拿过去就是运行不了，苦恼了两天了

**Comment by Kipiqid** [comment]
我已经尝试修改过了配置管理器，都使用x86或Win32平台进行编译，但是目前还是没有效果

**Comment by horsefaced** [comment]
可以试试

发自我的iPhone

**Comment by Kipiqid** [comment]
兄弟，我找到原因了，但是不知道怎么解决。。

https://www.it1352.com/472394.html

上述问题和我的问题是一样的，我把C++项目属性里的运行库改成了/MD，但是我可能需要/MT，这样就不需要用户本地安装运行库了，但是/CLR和/MD又不兼容，编译都不让编译。。我真的是走投无路了，不可能让每个客户都去装一个VS吧，你有遇到类似的问题吗？

**Comment by Kipiqid** [comment]
按道理安装了vc_redist以后应该就没问题了呀，我google了半天很多人都说是如此，但是现在的情况是我把vc_redist的各个版本都安装了还是不行。然后我给测试电脑安装了vs以后发现就能正常运行了，但是在我卸载了控制台里名为 “Windows Software Development Kit -Windows 10.0.18362.1” 的程序后就又跑不起来了。

**Comment by horsefaced** [comment]
你编译的是不是debug版本?

**Comment by Kipiqid** [comment]
牛逼，解决了
