### ISSUE TITLE
编译出错，缺少lib文件

### ISSUE THREAD

**Issue by ghost** [horsefaced/AgoraCLI#5]
错误	LNK1104	无法打开文件“MSVCMRT.lib”
@horsefaced

**Comment by horsefaced** [comment]
因为要用到Visual C++，所以你要安装vc的库

**Comment by ghost** [comment]
怎么安装的呢

**Comment by ghost** [comment]
能不能留你qq，谢谢啦

**Comment by horsefaced** [comment]
你安装visual studio的时候, 没选择安装 vc 部分吧?

**Comment by ghost** [comment]
全选的

**Comment by horsefaced** [comment]
QQ就算了, github还是按github的习惯来, 提交issue就行了, 有邮件提醒的.

**Comment by ghost** [comment]
我这边就是一直运行不出来

**Comment by ghost** [comment]
你的vs是什么版本的

**Comment by horsefaced** [comment]
那你找一下本机上 MSVCMRT.lib 这个东西有没有

**Comment by horsefaced** [comment]
2017

**Comment by ghost** [comment]
我2015，D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\msvcmrtd.lib
有这个

**Comment by ghost** [comment]
msvcmrt.lib，这个也有

**Comment by horsefaced** [comment]
https://stackoverflow.com/questions/33738779/visual-studio-12-0-missing-library-msvcmrt 这上面的方法你试试, 直接copy到运行目录下去

**Comment by ghost** [comment]
好的，我试试，不行再找你，感谢感谢！

**Comment by ghost** [comment]
AgoraClrLibrary编译出来了，生成dll，但是demo出错

“System.IO.FileNotFoundException”类型的未经处理的异常在 AgoraClrDemo.exe 中发生 
未能加载文件或程序集“AgoraClrLibrary.dll”或它的某一个依赖项

**Comment by horsefaced** [comment]
你没把编译出来AgoraClrLibrary.dl拷贝到bin的debug目录下去

**Comment by ghost** [comment]
拷了，试过debug、release都不好使

**Comment by horsefaced** [comment]
好, 那你把声网的几个dll放到debug目录下去了吗?

**Comment by ghost** [comment]
好使了，谢谢，感谢感谢感谢
