### ISSUE TITLE
android  跟pc端不通

### ISSUE THREAD

**Issue by KobeChe** [horsefaced/AgoraCLI#6]

**Comment by KobeChe** [comment]
您好   您测试过pc跟你Android之间通信吗

**Comment by horsefaced** [comment]
我用声网的例子程序试过

**Comment by KobeChe** [comment]
那就是说  c#您也测试过
但是刚才调试   跟Android视频通话  下面这个函数根本就没有执行  
![image](https://user-images.githubusercontent.com/23411356/28405305-4b567362-6d5f-11e7-85a4-ebdd98f7fe9e.png)

**Comment by horsefaced** [comment]
是的, 我测试过, 这个函数没有执行就说明你们两端有一边没有把图像传过来. 你拿一个声网的android例子,然后直接运行测试看看就知道是哪里出问题了, 一般问题会出在
1.  没有用同一个vendorkey
2. 没有加入同一个频道

**Comment by KobeChe** [comment]
我试了一遍必须的是手机先加入频道 这个方法才会执行  但是  从pc看到的手机端的画面是一个大黑板
手机端还是没有pc的画面

**Comment by horsefaced** [comment]
其实手机与PC哪个先都应该会执行这个方法. 
这个方法第一版本就已经加入进来了, 我公司用过, 还有群里一些人用过, 所以应该是没有问题的. 
所以,推荐你先试试到两个安卓能不能对通, 两个PC能不能对通, 然后再测试安卓与PC能不能对通.

**Comment by KobeChe** [comment]
pc与pc也没通     我想问您一下  joinchannel方法执行了就会推流吗？还是有专门的推流方法？    我们真的是没跑通

**Comment by KobeChe** [comment]
agora join channel success in 2222 by -1870508204 result is 227           出现这个提示信息  是说明成功了吗？？

**Comment by horsefaced** [comment]
要先打开摄像头, 用第一个按键去enableVideo才行

**Comment by horsefaced** [comment]
还有, PC对PC不能同一台机子哦

**Comment by KobeChe** [comment]
用的是两台pc   都能看见本地的视频    就是看不到对面的画面   看到您好像没有写推流的函数    是不是在joinchannel中推流的？

**Comment by KobeChe** [comment]
您能把跑成功的代码传给我一份吗      chezhonghao@163,com   谢谢

**Comment by horsefaced** [comment]
我就是用这个程序跑成功的啊, 没有另外的代码了.

**Comment by horsefaced** [comment]
而且推流不需要你手动去写, 只要enablevideo后, joinchannel就可以自动推了

**Comment by KobeChe** [comment]
能不能给我们发一个exe文件呀    我们明天演示   救命大侠

**Comment by horsefaced** [comment]
已经发送到你邮箱, 请参考邮件内容

**Comment by horsefaced** [comment]
还有, 推荐先按打开本地视频, 然后再按加入频道, 界面上的参数你可以先不修改, 直接试

**Comment by KobeChe** [comment]
谢谢谢       谢谢          但是程序只有用您的账号可以调通   是为啥呢

**Comment by horsefaced** [comment]
呃, 这个我不太清楚, DEMO已经写了很久了, 可能在DEMO里写上我的KEY了吧. 不过library里面应该是中立的, 你们可以随便用.

**Comment by KobeChe** [comment]
解决了   谢谢您

**Comment by horsefaced** [comment]
呃, 是什么问题? 我收集一下, 以后有人问差不多的问题也好快速回.

**Comment by KobeChe** [comment]
不好意思啊   没看到   就是因为你joinchannel的时候开启了验证  所以参数传的是一个空格   我们没有开启验证   把参数中的空格改成null就可以了
