### ISSUE TITLE
ClrVideoFrame

### ISSUE THREAD

**Issue by lauix** [horsefaced/AgoraCLI#8]
构造函数和writeRaw函数中的size变量计算错误了，size应该是宽和高的积，不是和。

AgoraClrLibrary.h:257
int size = width * height;

AgoraClrLibrary.h:267
int sizeModified = (raw.width * raw.height) == (width * height);

AgoraClrLibrary.h:271
int size = width * height;

**Comment by horsefaced** [comment]
收到, 我去看一下

**Comment by horsefaced** [comment]
已经修改, 谢谢反馈
