### ISSUE TITLE
对这个项目很感兴趣，能否私底下询问一些技术问题？

### ISSUE THREAD

**Issue by incomment7336** [horsefaced/AgoraCLI#9]
对这个项目很感兴趣，能否私底下询问一些技术问题？
目前也是遇到各种C++到C#转换的问题，因为很多SDK都基于C++开发，高效，可以理解。但业务系统很多都是基于C# Java之类开发。

**Comment by horsefaced** [comment]
可以啊, 不过我其实C++也不太熟悉, 所以不一定能帮上你多少忙, 还请见谅.
